### ISSUE TITLE
Change NPC to Enemy for ts-game-jam-1

### ISSUE THREAD

**Issue by sglucchini** [thoughtstem/TS-Kata-Collections#11]
update NPC katas to create an enemy instead.

- has sword
- follows you
- zombie/slime that hurts you by touch?
- no weapons for avatar, must be fitting difficulty

**Comment by sglucchini** [comment]
Also update Game Jam lists NPC -> Enemy

**Comment by aBlender** [comment]
Enemies randomize between a bat, slime, and snake that shoots acid bubbles at you.
Having a sword would have required a smarter ai state machine

Here's a working example (also found at the bottom of survival-game-jam.rkt)

```
#:enemy-list (list (custom-enemy #:sprite bat-sprite
                                    #:ai 'medium
                                    #:amount-in-world 5)
                      (custom-enemy #:sprite slime-sprite
                                    #:ai 'easy
                                    #:amount-in-world 10)
                      ; adding curry allows each enemy to have a random sprite
                      (curry custom-enemy #:amount-in-world 10)
                      )
```
