### ISSUE TITLE
Include day/night cycles in ts-survival katas

### ISSUE THREAD

**Issue by sglucchini** [thoughtstem/TS-Kata-Collections#12]
include day/night cycles in katas
tech not yet complete

**Comment by aBlender** [comment]
Tech is complete, here are the options and their defaults:

`(custom-sky #:night-sky-color  [color      'black]
                     #:length-of-day    [day-length 2400]
                      #:start-of-daytime [day-start #f]
                      #:end-of-daytime   [day-end   #f]
                      #:max-darkness     [max-alpha 160])`

**Comment by aBlender** [comment]
Katas are done
