### ISSUE TITLE
Offensive base katas

### ISSUE THREAD

**Issue by srfoster** [thoughtstem/TS-Kata-Collections#5]
Need katas for "Offensive base" -- rocket towers, etc.

**Comment by srfoster** [comment]
Make a new section and include it in manual.scrbl

**Comment by srfoster** [comment]
Tables:
1) Rocket Tower (Homing?)
2) Repeater Tower
3) Dagger Tower
4) Avatar
5) Enemy

**Comment by sglucchini** [comment]
Bronze for all three towers complete.

Plan for specialization in silver, gold or platinum katas: 
- Rocket tower, make it a homing rocket
- dagger tower, change the number of daggers/spread
- repeater tower, change fire rate?
